numbers = list(range(1, 1000000))

# Iterate through the list of numbers, pick a random single one and print it
import random
random_number = random.choice(numbers)
print(f"Randomly selected number: {random_number}")
print (f"did you know that the number {random_number} is a random choice from a list of numbers 1 to 1000000?")
print ("I hope you find this number interesting!")
print ("I hope you find this game cool!")
print ("I hope that you enjoyed this simulation of...")
print ("r")
print ("a")
print ("n")
print ("d")
print ("o")
print ("m")
print ("n")
print ("e")
print ("s")
print ("s")